import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Header from "./components/common/Header";
import SideMenu from "./components/common/SideMenu";
import Footer from "./components/common/Footer";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "@fontsource/ubuntu"; // Defaults to weight 400
import "@fontsource/ubuntu/400.css"; // Specify weight
import "@fontsource/ubuntu/400-italic.css"; // Specify weight and style

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ADBL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{fontFamily:"Ubuntu"}}>
        <Header />
        <SideMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
